# Generated by Django 3.2.5 on 2021-11-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_work_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grader_sh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('submission', models.FileField(upload_to='None/graded_csv/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.work')),
            ],
        ),
        migrations.CreateModel(
            name='Graded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('submission', models.FileField(upload_to='None/graded_csv/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.work')),
            ],
        ),
    ]
